# Generated by Django 5.2.4 on 2025-09-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("words", "0009_remove_word_categories_delete_category"),
        ("words_collections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"verbose_name": "коллекцию", "verbose_name_plural": "коллекции"},
        ),
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создана"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_close",
            field=models.BooleanField(default=False, verbose_name="закрытая"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=120, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="users.user",
                verbose_name="владелец",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлена"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="words",
            field=models.ManyToManyField(
                related_name="collections", to="words.word", verbose_name="слова"
            ),
        ),
    ]
