# Generated by Django 5.2.4 on 2025-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        (
            "words_collections",
            "0002_alter_collection_options_alter_collection_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="saved_collections",
                to="users.user",
                verbose_name="пользователи",
            ),
        ),
    ]
