# Generated by Django 5.2.4 on 2025-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words_collections", "0003_collection_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="words",
        ),
        migrations.AddField(
            model_name="collection",
            name="data",
            field=models.JSONField(default=dict, verbose_name="данные"),
        ),
    ]
