# Generated by Django 5.2.4 on 2025-09-21 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("words_collections", "0004_remove_collection_words_collection_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections_owner",
                to="users.user",
                verbose_name="владелец",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections_saved",
                to="users.user",
                verbose_name="пользователи",
            ),
        ),
    ]
