# Generated by Django 5.1.5 on 2025-07-13 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hebrew_name",
                    models.CharField(max_length=120, verbose_name="название на иврите"),
                ),
                (
                    "russian_name",
                    models.CharField(
                        max_length=120, verbose_name="название на русском"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hebrew_word",
                    models.CharField(max_length=120, verbose_name="слово на иврите"),
                ),
                (
                    "russian_word",
                    models.CharField(max_length=120, verbose_name="слово на русском"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="информация"
                    ),
                ),
                (
                    "pealim_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="ссылка на Pealim"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="words.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "слово",
                "verbose_name_plural": "слова",
            },
        ),
    ]
