# Generated by Django 5.1.5 on 2025-07-13 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="russian_word",
        ),
    ]
