# Generated by Django 5.1.5 on 2025-07-13 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0002_remove_word_russian_word"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
    ]
