# Generated by Django 5.1.5 on 2025-07-13 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="создан",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлен"),
        ),
    ]
