# Generated by Django 5.1.5 on 2025-07-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0004_word_created_at_word_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="hebrew_name",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="название на иврите"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="hebrew_word",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="слово на иврите"
            ),
        ),
    ]
