# Generated by Django 5.1.5 on 2025-07-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0005_alter_category_hebrew_name_alter_word_hebrew_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="analyzed",
            field=models.BooleanField(default=False, verbose_name="анализирован"),
        ),
    ]
