# Generated by Django 5.1.5 on 2025-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0006_word_analyzed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="category",
        ),
        migrations.AddField(
            model_name="word",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                to="words.category",
                verbose_name="категория",
            ),
        ),
    ]
