# Generated by Django 5.1.5 on 2025-07-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0007_remove_word_category_word_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="multiply",
            field=models.BooleanField(default=False, verbose_name="множественное"),
        ),
    ]
