# Generated by Django 5.2.4 on 2025-09-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0008_word_multiply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
